"""The ingestion clean-transform oracle (specs/data.md "Evaluation contract": golden = transforms).

``clean_snapshot(tests/golden/raw)`` must reproduce the committed ``expected/`` cleaned
tables. Comparison is via ``assert_frame_equal`` on CSV (not byte-Parquet): both sides are
round-tripped through CSV so dtype inference is identical and the assertion tests the
transform's values/shape, not Parquet encoding.

The golden set is REAL PUBLIC AACT trial-level data with NO PHI and NO synthetic rows; the
expected outputs were generated by this same transform, never hand-authored.
"""

from __future__ import annotations

import io
import json
from pathlib import Path

import pandas as pd

from ingestion.clean import clean_snapshot
from ingestion.config import GOLDEN_RAW_ROOT, GOLDEN_ROOT
from ingestion.report import QualityReport

_EXPECTED = ("ref_trial", "ref_arm", "ref_withdrawal_reason")


def _csv_roundtrip(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise a frame through CSV so dtypes match a freshly read expected CSV."""
    return pd.read_csv(io.StringIO(df.to_csv(index=False)))


def test_golden_oracle_reproduces_expected(clean_frames) -> None:
    for name in _EXPECTED:
        expected = pd.read_csv(GOLDEN_ROOT / "expected" / f"{name}.csv")
        fresh = _csv_roundtrip(clean_frames[name])
        pd.testing.assert_frame_equal(fresh, expected)


def test_golden_clean_eligible_no_validation_failures(golden_report) -> None:
    """Every golden NCT is clean-eligible by construction — the transform never fails on it."""
    assert golden_report.validation_failures == []


def test_golden_selection_covers_every_required_stratum() -> None:
    """The selection is deterministic and spans the full required cross product (fail-loud)."""
    sel = json.loads((GOLDEN_ROOT / "selection.json").read_text(encoding="utf-8"))
    n_cells = sel["selection_rule"]["n_cells"]
    per_cell = sel["selection_rule"]["per_cell"]
    assert len(sel["cells"]) == n_cells
    assert all(len(ncts) == per_cell for ncts in sel["cells"].values())
    assert sel["n_ncts"] == n_cells * per_cell
    assert sel["provenance"]["synthetic"] is False


def test_golden_raw_is_real_public_no_phi() -> None:
    """The slice manifest declares REAL public AACT provenance, NO PHI, NO synthetic."""
    manifest = json.loads(
        (GOLDEN_RAW_ROOT / "manifest.json").read_text(encoding="utf-8")
    )
    assert manifest["golden_subset"] is True
    assert "NO PHI" in manifest["disclaimer"]
    assert "synthetic" not in manifest.get("source_kind", "").lower() or (
        "not synthetic" in manifest["source_kind"].lower()
    )


def test_clean_snapshot_on_golden_matches_oracle(golden_raw_root: Path) -> None:
    """A direct clean of the committed golden raw reproduces the committed expected CSVs."""
    report = QualityReport()
    import tempfile

    frames = clean_snapshot(
        golden_raw_root,
        report=report,
        out_root=Path(tempfile.mkdtemp()),
        live=False,
        fail_loud=True,
    )
    for name in _EXPECTED:
        expected = pd.read_csv(GOLDEN_ROOT / "expected" / f"{name}.csv")
        pd.testing.assert_frame_equal(_csv_roundtrip(frames[name]), expected)
