"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { StatusDot, StatusType } from "./status-dot"

interface ExplanationCardProps {
  participantId: string
  riskScore: number
  explanation: string
  className?: string
}

function getStatus(value: number): StatusType {
  if (value < 40) return "calm"
  if (value < 70) return "watch"
  return "risk"
}

function getStatusLabel(status: StatusType): string {
  switch (status) {
    case "calm": return "Low Risk"
    case "watch": return "Moderate Risk"
    case "risk": return "High Risk"
  }
}

export function ExplanationCard({
  participantId,
  riskScore,
  explanation,
  className,
}: ExplanationCardProps) {
  const status = getStatus(riskScore)
  
  return (
    <Card className={cn("border-[0.5px] border-border shadow-sm", className)}>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium text-foreground flex items-center gap-2">
          <svg
            className="h-4 w-4 text-muted-foreground"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={1.5}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z"
            />
          </svg>
          Risk Explanation
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center gap-2 text-sm">
          <StatusDot status={status} size="md" />
          <span className="font-medium text-foreground">{getStatusLabel(status)}</span>
          <span className="text-muted-foreground">
            ({riskScore}% dropout probability)
          </span>
        </div>
        
        <div className="border-l-2 border-border pl-4 py-1">
          <p className="text-sm text-foreground leading-relaxed">
            {explanation}
          </p>
        </div>
        
        <p className="text-xs text-muted-foreground">
          This summary is assembled from the model&apos;s risk outputs (not generated by the model)
          and should be reviewed by clinical staff.
        </p>
      </CardContent>
    </Card>
  )
}
